### ISSUE TITLE
Why not have took Midori/Aka or even the later Ao to make english translation, instead of transforming Blue into Mirori/Aka to translate?

### ISSUE THREAD

**Issue by bphd** [Dracrius/pocketrgb-en#11]
(Along with other bugfix and enhancments made like SGB...)

**Comment by Dracrius** [comment]
The English version was used over the reverse as it was the only sensible why to proceed as someone who doesn't speak Japanese at all. It is far easier to search for words in my own language and correct the much smaller number of differences then it would be to LITERALLY translate the entire game with no knowledge of the language. Using the Japanese releases would have resulted in 100x more bugs and issues especially seeing as the character tables are not compatible. A lot of code changes were made just to handle that in the English releases. Other projects have attempted this but it brings many many other issues. 

On the point of the bugfixes and enhancements though that is just obvious if bug fixes are listed and available it seems wrong not to implement them. We are republishing an old classic no reason to keep it broken or re-brake it in the ways never intended. All fixes are documented Pokered fixes and 99% of them are ripped right from yellow and 100% of them are not intended by the original developers. This was my way of deciding ie I did none of the balancing or quality of life enhancements. Also SGB color palettes are optional but there for those who want to play in color on original hardware!!

**Comment by bphd** [comment]
Some people tells that there is so few differences between Midori/Aka and Blue that it's the same taking one or the other and now you tell that it's so different that taking Midori/Aka would be a big challenge to begin with, curious

But anyway, I understand better the why, thanks!

Maybe one more dumb question, but that version could be used as Blue? Like using same cheat code, or the binary code was shifted so no memory codes of Blue are the same so cheat codes won't work?
