### ISSUE TITLE
PocketRGB-EN (NOT DX) Green and Red Patches don't work.

### ISSUE THREAD

**Issue by nanashi89** [Dracrius/pocketrgb-en#6]
Downloaded the most recent patches for EN from ROMHacking.net. Upon loading Green and Red, they just give me a blank screen.

Blue works fine, tho.

**Comment by Dracrius** [comment]
Thanks I'm looking into it now not sure what happened there but I'll get it fixed!

**Comment by Dracrius** [comment]
> 

Romhacking always takes a day to update things once I send it so grab the fixed patches from the release section I fixed them. The same happened with DX it seems and it is quit random I'll just double check the patches in the future apologies!!
